# Generated by Django 4.2.7 on 2024-02-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzurePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('retail_price', models.FloatField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('meter', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
